### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by shriraj20**
install vk notifications from GitHub marketplace under chat using action

### CODE REVIEW

**Comment by HereIsKevin** [comment]
What is the purpose of VK Notifications? I can't seem to find anything about it other than its usage.

**Comment by shriraj20** [comment]
To give notifications to people about updates.
Thanks,
Shriraj Dash

**Comment by HereIsKevin** [comment]
How does it give the notifications?

**Comment by shriraj20** [comment]
We need to create Vk account and do the integrations for the website and if
we post any messages then in vk website it will popup to the viewers.
Thanks,
Shriraj Dash

**Comment by HereIsKevin** [comment]
It seems like this is impractical because this would be like requiring everyone to sign up for VK.

**Comment by HereIsKevin** [comment]
I'll close this for now, and reopen it when you respond

**Comment by shriraj20** [comment]
not everyone like one person and share the username and password with
everyone
Thanks,
Shriraj Dash

**Comment by HereIsKevin** [comment]
Isn't there going to be a security problem if usernames and passwords are shared? People could change the password and lock everyone out, or the password could be leaked.

**Comment by shriraj20** [comment]
only with us ojas yajat me pranav
Thanks,
Shriraj Dash

**Comment by HereIsKevin** [comment]
OK, I'll merge after I find out more on how to use this GitHub action.

**Comment by HereIsKevin** [comment]
What's the point of using VK, though, when we already have Google Hangouts. GitHub integration is not necessary.

**Pull request closed without merging**
